apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
    tier: backend
spec:
  ports:
    - port: 8083
  selector:
    app: catalog-service
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  selector:
    matchLabels:
      app: catalog-service
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog-service
        tier: backend
    spec:
      containers:
        - name: catalog-service
          image: localhost:5000/it4root/catalog-service:latest
          ports:
            - containerPort: 8083
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: catalog-service
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: myhomework
      http:
        paths:
          - backend:
              serviceName: catalog-service
              servicePort: 8083
            path: /catalogs(/|$)(.*)
