spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: catalog_u
    password: catalog_p
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8083
